version: '3.8'
services:

  # Este é o banco de dados SOURCE com os dados mockados
  postgres_source_server:

    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: senhasourcedb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "10000:5432"
    volumes:
      - ./data_src:/var/lib/postgresql/data
      - ./init_src.sql:/docker-entrypoint-initdb.d/init_src.sql
    networks:
      - test_analist


  # Este é o banco de dados TARGET o qual irá conter os dados analisados
  postgres_target_server:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: senhatargetdb
    ports:
      - "11000:5432"
    volumes:
      - ./data_trg:/var/lib/postgresql/data
      - ./init_target.sql:/docker-entrypoint-initdb.d/init_src.sql
    networks:
      - test_analist

networks:
  test_analist:
    name: test_analist
    driver: bridge